# Generated by Django 5.1 on 2024-09-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortlistedPoliceStation',
            fields=[
                ('sr', models.AutoField(primary_key=True, serialize=False)),
                ('police_name', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('state_ut', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'bestpolice_shortlistedpolicestation',
            },
        ),
    ]
