# Generated by Django 5.1 on 2024-09-13 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestPolice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortlistedPoliceStationAddress',
            fields=[
                ('addId', models.AutoField(primary_key=True, serialize=False)),
                ('address_line1', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('sr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestPolice.shortlistedpolicestation')),
            ],
        ),
    ]
