# Generated by Django 5.1 on 2024-09-13 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestPolice', '0003_rename_city_shortlistedpolicestationaddress_state'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shortlistedpolicestationaddress',
            table='address',
        ),
    ]
